---
# Initial new player parameters
player:
  sprite: player-sprite.png

  stats:
    maxAcceleration: 4000.0 # Applied immediately on key press
    maxSpeed: 400.0
    deceleration: 800.0

    health: 100.0
    maxHealth: 100.0
    regenRate: 10.0

    armor: 0.0
    armorPenetration: 0.0

    attackRange: 100.0
    attackPower: 10.0
    attackCooldown: 1.0

    critChance: 0.0
    critMultiplier: 2.0

    mass: 1.0

# Generic enemy parameters
enemy:
  sprite: enemy-sprite.png

  healthBar:
    height: 7.0
    padding: 2.0

    backgroundColor: 0xFF000000
    fillColor: 0xFF4CAF50
    enableNumericDisplay: true

  stats:
    # maxAcceleration: 200.0 # Enemies are velocity controlled
    maxSpeed: 100.0
    deceleration: 0.0 # Enemies are velocity controlled

    health: 100.0
    maxHealth: 100.0
    regenRate: 0.0

    armor: 0.0
    armorPenetration: 0.0

    attackRange: 60.0
    attackPower: 10.0
    attackCooldown: 1.0

    critChance: 0.0
    critMultiplier: 2.0

    mass: 1.0

# Zombie enemy parameters
zombie:
  sprite: zombie-sprite.png

  stats:
    maxSpeed: 60.0

    maxHealth: 200.0
    regenRate: 40.0

    attackRange: 100.0
    attackPower: 20.0

    mass: 4.0

# Goblin enemy parameters
goblin:
  sprite: goblin-spritesheet.png

  stats:
    maxSpeed: 250.0

    health: 50.0
    maxHealth: 50.0

    attackRange: 40.0

    critChance: 90.0

    mass: 0.8

# Robot enemy parameters
robot:
  # sprite: 
  
  stats:
    maxSpeed: 175.0

    health: 100.0
    maxHealth: 100.0

    armor: 20.0
    armorPenetration: 10.0

    attackRange: 150.0
    attackPower: 20.0

    mass: 2.2