version: "3"

services:
  mongo:
    image: mongo:5.0.13
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - rogalik_network
    volumes:
      - ./db/mongo:/data/db
  postgres:
    image: postgres:14.1-alpine
    networks:
      - rogalik_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  rogalik_backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - rogalik_network
    restart: on-failure

networks:
  rogalik_network:
    driver: bridge
