name: Build Game workflow

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare tag
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's|/|-|g' | tr '[:upper:]' '[:lower:]')
          echo "FULL_TAG=${REPO_LOWER}:${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ env.FULL_TAG }}
